config/routes.rb
Rails.application.routes.draw do

  root to: 'fsjs_main#index'
  resources :fsjs_capitals
  resources :fsjs_journals
  resources :fsjs_accounts
  
  get  '/login', to: 'fsjs_login#new'
  post '/login', to: 'fsjs_login#create'
  delete '/logout', to: 'fsjs_login#destroy'
  
end

app/models/fsjs_account.rb
class FsjsAccount < ApplicationRecord

  validates :name, length: { maximum: 20 }, presence: true, uniqueness: true
  validates :types,        presence: true
  validates :sort_list,    presence: true, length: { maximum: 5 }
  validates :sort_expense, presence: true, length: { maximum: 5 }
  
  validates :types,  numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 3 } , unless: Proc.new { |a| a.types.blank? } 
  
end

app/controllers/fsjs_accounts_controller.rb
class FsjsAccountsController < ApplicationController
  before_action :set_fsjs_account, only: [:show, :edit, :update, :destroy]
  
  before_action :fsjs_get_account_types_combobox
  helper_method :fsjs_get_account_types_from_id
    
  # GET /fsjs_accounts
  def index
    @fsjs_accounts = FsjsAccount.all.order(sort_list: "ASC")
  end

  # GET /fsjs_accounts/1
  def show
  end

  # GET /fsjs_accounts/new
  def new
    @fsjs_account = FsjsAccount.new
  end

  # GET /fsjs_accounts/1/edit
  def edit
  end

  # POST /fsjs_accounts
  def create
    @fsjs_account = FsjsAccount.new(fsjs_account_params)

    respond_to do |format|
      if @fsjs_account.save
        format.html { redirect_to fsjs_accounts_path, notice: '登録しました。' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /fsjs_accounts/1
  def update
    respond_to do |format|
      if @fsjs_account.update(fsjs_account_params)
        format.html { redirect_to fsjs_accounts_path, notice: '更新しました。' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /fsjs_accounts/1
  def destroy
    @fsjs_account.destroy
    respond_to do |format|
      format.html { redirect_to fsjs_accounts_url, alert: '削除しました。' }
    end
  end

  private
    # コンボボックス用 - 種類
    def fsjs_get_account_types_combobox()
      @fsjs_account_types_list = []
      @fsjs_account_types_list.push(['借方',1])
      @fsjs_account_types_list.push(['貸方',2])
      @fsjs_account_types_list.push(['借方 + 貸方',3])
    end  

    # idから種類を取得する 
    def fsjs_get_account_types_from_id(id)
     @fsjs_account_types_list.each_with_index do |obj,i|
       if(obj[1] == id)
         return obj[0]
       end  
     end
     return "";
    end  
        
    # Use callbacks to share common setup or constraints between actions.
    def set_fsjs_account
      @fsjs_account = FsjsAccount.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fsjs_account_params
      params.require(:fsjs_account).permit(:name, :types, :expense_flg, :sort_list, :sort_expense)
    end
end

app/helpers/fsjs_accounts_helper.rb
module FsjsAccountsHelper
end

app/views/fsjs_accounts/_form.html.slim
= form_with(model: @fsjs_account, local: true) do |f|
  - if @fsjs_account.errors.any?
    #error_explanation.text-danger
      ul
        - @fsjs_account.errors.full_messages.each do |message|
          li = message

  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control', id: 'fsjs_account_name'
  .form-group
    = raw '<label for="fsjs_account_types">種類</label>'
    br
    - if @fsjs_account.types.present?    
      = f.select :types, options_for_select(@fsjs_account_types_list,@fsjs_account.types),include_blank: '選択して下さい。',id: 'fsjs_account_types'
    - else
      = f.select :types, options_for_select(@fsjs_account_types_list),include_blank: '選択して下さい。',id: 'fsjs_account_types'    
  .form-group style= "float:left;"
    = f.label :expense_flg
    = f.check_box :expense_flg, class: 'form-control', id: 'fsjs_account_expense_flg'
  .clearfix    
  .form-group
    = f.label :sort_list
    = f.number_field :sort_list, class: 'form-control', id: 'fsjs_account_sort_list'
  .form-group
    = f.label :sort_expense
    = f.number_field :sort_expense, class: 'form-control', id: 'fsjs_account_sort_expense'
  
  br
  br
  = f.submit yield(:submit) , class: 'btn btn-primary'  

app/views/fsjs_accounts/edit.html.slim
- provide(:title, '勘定科目 - 編集')
- provide(:submit, '更新する')

nav aria-label="breadcrumb"
  ol.breadcrumb
    li.breadcrumb-item =link_to("ホーム", root_path) 
    li.breadcrumb-item =link_to("勘定科目", fsjs_accounts_path)     
    li.breadcrumb-item.active aria-current="page" = '編集'

p
h1 勘定科目の編集
p

= render 'form'

br
br
= link_to '戻る', fsjs_accounts_path
p

nav aria-label="breadcrumb"
  ol.breadcrumb
    li.breadcrumb-item =link_to("ホーム", root_path) 
    li.breadcrumb-item =link_to("勘定科目", fsjs_accounts_path)     
    li.breadcrumb-item.active aria-current="page" = '編集'

p    

app/views/fsjs_accounts/index.html.slim
- provide(:title, '勘定科目')

nav aria-label="breadcrumb"
  ol.breadcrumb
    li.breadcrumb-item =link_to("ホーム", root_path) 
    li.breadcrumb-item.active aria-current="page" = '勘定科目'
    
p
h1 勘定科目
p

= raw '<p>この画面は<span style="color:red;">システム設定</span>です。複式簿記がわからない方は操作しないでください。</p>'

p
  = raw "「損益計算書」で利用できる経費の科目は全て登録済みです。その他に必要であれば追加して下さい。"
  = raw '<br>※不要な経費の科目は削除して頂いても構いません。'
  = raw '<br>※誤って変更した場合は「fsjs_accounts.csv」を使用すればデータを復元できます。'

table.table.table-hover
  thead 
    tr
      th = FsjsAccount.human_attribute_name(:name)
      th = FsjsAccount.human_attribute_name(:types)
      th = FsjsAccount.human_attribute_name(:expense_flg)
      th = FsjsAccount.human_attribute_name(:sort_list)
      th = FsjsAccount.human_attribute_name(:sort_expense)
      th
  - @fsjs_accounts.each do |fsjs_account|
    tr
      td
        = link_to fsjs_account.name, fsjs_account
      td
        = fsjs_get_account_types_from_id(fsjs_account.types)
      td
        = fsjs_account.expense_flg
      td
        = fsjs_account.sort_list
      td
        = fsjs_account.sort_expense
      td
        = link_to '編集', edit_fsjs_account_path(fsjs_account), class: 'btn btn-primary' 
        = raw "&nbsp;&nbsp;&nbsp;"
        = link_to '削除', fsjs_account, method: :delete, data: { confirm: "\n#{fsjs_account.name} を削除します。よろしいですか？"  }, class: 'btn btn-danger' 

br
= link_to '勘定科目の新規登録', new_fsjs_account_path,class: 'btn btn-primary'  

br
br
br

nav aria-label="breadcrumb"
  ol.breadcrumb
    li.breadcrumb-item =link_to("ホーム", root_path) 
    li.breadcrumb-item.active aria-current="page" = '勘定科目'

p      

app/views/fsjs_accounts/new.html.slim
- provide(:title, '勘定科目 - 新規登録')
- provide(:submit, '登録する')

nav aria-label="breadcrumb"
  ol.breadcrumb
    li.breadcrumb-item =link_to("ホーム", root_path) 
    li.breadcrumb-item =link_to("勘定科目", fsjs_accounts_path)     
    li.breadcrumb-item.active aria-current="page" = '新規作成'

p
h1 新規登録 - 勘定科目
p

= render 'form'

br
br
= link_to '戻る', fsjs_accounts_path
p

nav aria-label="breadcrumb"
  ol.breadcrumb
    li.breadcrumb-item =link_to("ホーム", root_path) 
    li.breadcrumb-item =link_to("勘定科目", fsjs_accounts_path)     
    li.breadcrumb-item.active aria-current="page" = '新規作成'

p    

app/views/fsjs_accounts/show.html.slim
- provide(:title, '勘定科目 - 表示')

nav aria-label="breadcrumb"
  ol.breadcrumb
    li.breadcrumb-item =link_to("ホーム", root_path) 
    li.breadcrumb-item =link_to("勘定科目", fsjs_accounts_path)     
    li.breadcrumb-item.active aria-current="page" = '表示'
    

table.table.table-hover 
  tr
    th style="width:200px;" = FsjsAccount.human_attribute_name(:name)
    td = @fsjs_account.name
  tr
    th = FsjsAccount.human_attribute_name(:types)
    td = @fsjs_account.types
  tr
    th = FsjsAccount.human_attribute_name(:expense_flg)
    td = @fsjs_account.expense_flg
  tr
    th = FsjsAccount.human_attribute_name(:sort_list)
    td = @fsjs_account.sort_list
  tr
    th = FsjsAccount.human_attribute_name(:sort_expense)
    td = @fsjs_account.sort_expense
  tr
    th = "最終更新日"
    td = @fsjs_account.updated_at.to_s.sub(/\+0900/, '') 

div
  div.float-right
    span = link_to '編集', edit_fsjs_account_path(@fsjs_account), class: 'btn btn-primary' 
    span = raw "&nbsp;&nbsp;&nbsp;"
    span = link_to '削除', @fsjs_account, data: { confirm: "\n#{@fsjs_account.name} を削除します。\nよろしいですか？" }, method: :delete, class: 'btn btn-danger' 
  div.float-left
    = link_to '戻る', fsjs_accounts_path
div.clearfix    

p

nav aria-label="breadcrumb"
  ol.breadcrumb
    li.breadcrumb-item =link_to("ホーム", root_path) 
    li.breadcrumb-item =link_to("勘定科目", fsjs_accounts_path)     
    li.breadcrumb-item.active aria-current="page" = '表示'
    
p    