config/routes.rb
Rails.application.routes.draw do

  root to: 'fsjs_main#index'
  resources :fsjs_capitals
  resources :fsjs_journals
  resources :fsjs_accounts
  
  get  '/login', to: 'fsjs_login#new'
  post '/login', to: 'fsjs_login#create'
  delete '/logout', to: 'fsjs_login#destroy'
  
end

app/models/fsjs_capital.rb
class FsjsCapital < ApplicationRecord
  validates :yyyy,  presence: true, uniqueness: true
  validates :yyyy, numericality: { greater_than_or_equal_to: 1989, less_than_or_equal_to: 2099 } , unless: Proc.new { |a| a.yyyy.blank? }
  validates :m1,    presence: true, length: { maximum: 10 }
  validates :m1,    numericality: { greater_than_or_equal_to: 0 } , unless: Proc.new { |a| a.m1.blank? }     
  validates :m2,    presence: true, length: { maximum: 10 }
  validates :m2,    numericality: { greater_than_or_equal_to: 0 } , unless: Proc.new { |a| a.m2.blank? }   
  validates :m3,    presence: true, length: { maximum: 10 }
  validates :m3,    numericality: { greater_than_or_equal_to: 0 } , unless: Proc.new { |a| a.m3.blank? }   
  validates :m4,    presence: true, length: { maximum: 10 }
  validates :m4,    numericality: { greater_than_or_equal_to: 0 } , unless: Proc.new { |a| a.m4.blank? }   
end

app/controllers/fsjs_capitals_controller.rb
class FsjsCapitalsController < ApplicationController
  before_action :set_fsjs_capital, only: [:show, :edit, :update, :destroy]

  # GET /fsjs_capitals
  def index
    @fsjs_capitals = FsjsCapital.all.order(yyyy: "DESC")
  end

  # GET /fsjs_capitals/1
  def show
  end

  # GET /fsjs_capitals/new
  def new
    @fsjs_capital = FsjsCapital.new
  end

  # GET /fsjs_capitals/1/edit
  def edit
  end

  # POST /fsjs_capitals
  def create
    @fsjs_capital = FsjsCapital.new(fsjs_capital_params)

    respond_to do |format|
      if @fsjs_capital.save
        format.html { redirect_to fsjs_capitals_path, notice: '登録しました。' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /fsjs_capitals/1
  def update
    respond_to do |format|
      if @fsjs_capital.update(fsjs_capital_params)
        format.html { redirect_to fsjs_capitals_path, notice: '更新しました。' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /fsjs_capitals/1
  def destroy
    @fsjs_capital.destroy
    respond_to do |format|
      format.html { redirect_to fsjs_capitals_url, alert: '削除しました。' }
    end
    
    # 必要であれば、該当年度の仕訳帳も削除して下さい。
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fsjs_capital
      @fsjs_capital = FsjsCapital.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fsjs_capital_params
      params.require(:fsjs_capital).permit(:yyyy, :m1, :m2, :m3, :m4)
    end
end

app/helpers/fsjs_capitals_helper.rb
module FsjsCapitalsHelper
end

app/views/fsjs_capitals/_form.html.slim
= form_with(model: @fsjs_capital, local: true) do |f|
  - if @fsjs_capital.errors.any?
    #error_explanation.text-danger
      ul
        - @fsjs_capital.errors.full_messages.each do |message|
          li = message
          
  .form-group
    = raw '<label for="fsjs_capital_yyyy">年 ※西暦4桁</label>'
    = f.number_field :yyyy, class: 'form-control', id: 'fsjs_capital_yyyy'

  div.alert.alert-primary role="alert"
    =  '以下の4項目は1月1日(期首) 時点の「元入金」の金額を入力します。'
    br
    = '※ない場合は0を入力。繰越の場合は前年の12/31(期末)の金額を入力。'

  .form-group
    = f.label :m1      
    = f.number_field :m1, class: 'form-control', id: 'fsjs_capital_m1'
  .form-group
    = raw '<label for="fsjs_capital_m2">その他の預金 ※通帳の残高</label>'
    = f.number_field :m2, class: 'form-control', id: 'fsjs_capital_m2'
  .form-group
    = raw '<label for="fsjs_capital_m3">前払金 ※電子マネーの前払金など</label>'
    = f.number_field :m3, class: 'form-control', id: 'fsjs_capital_m3'
  .form-group
    = raw '<label for="fsjs_capital_m4">未払金 ※クレジットカードの未払金など</label>'
    = f.number_field :m4, class: 'form-control', id: 'fsjs_capital_m4'           
  
  br
  br
  = f.submit yield(:submit) , class: 'btn btn-primary'  

app/views/fsjs_capitals/edit.html.slim
- provide(:title, '会計年度 - 編集')
- provide(:submit, '更新する')

nav aria-label="breadcrumb"
  ol.breadcrumb
    li.breadcrumb-item =link_to("ホーム", root_path) 
    li.breadcrumb-item =link_to("会計年度", fsjs_capitals_path)     
    li.breadcrumb-item.active aria-current="page" = '編集'

p
h1 会計年度の編集
p

= render 'form'

br
br
= link_to '戻る', fsjs_capitals_path
p

nav aria-label="breadcrumb"
  ol.breadcrumb
    li.breadcrumb-item =link_to("ホーム", root_path) 
    li.breadcrumb-item =link_to("会計年度", fsjs_capitals_path)     
    li.breadcrumb-item.active aria-current="page" = '編集'

p    

app/views/fsjs_capitals/index.html.slim
- provide(:title, '会計年度')

nav aria-label="breadcrumb"
  ol.breadcrumb
    li.breadcrumb-item =link_to("ホーム", root_path) 
    li.breadcrumb-item.active aria-current="page" = '会計年度'
    
p
h1 会計年度
p
p
   = raw "「元入金」とは新規開業または前年からの繰越の金額です。 "
   
-logger.debug(111)
-logger.debug(FsjsCapital.human_attribute_name(:yyyy))
table.table.table-hover 
  thead
    tr
      th style="width:100px;"
      th 
      th = "元入金"
      th
  - @fsjs_capitals.each do |capital|
    tr
      td
        = link_to '仕訳帳', fsjs_journals_path(yyyy: capital.yyyy), class: 'btn btn-outline-info'      
      td
        = capital.yyyy.to_s() + "年"
        /= link_to(capital.yyyy.to_s() + "年", capital)
      td       
        = FsjsCapital.human_attribute_name(:m1) + " " + capital.m1.to_s(:delimited) + " "   
        = FsjsCapital.human_attribute_name(:m2) + " " + capital.m2.to_s(:delimited) + " "   
        = FsjsCapital.human_attribute_name(:m3) + " " + capital.m3.to_s(:delimited) + " "   
        = FsjsCapital.human_attribute_name(:m4) + " " + capital.m4.to_s(:delimited)    
      td
        = link_to '編集', edit_fsjs_capital_path(capital), class: 'btn btn-primary' 
        = raw "&nbsp;&nbsp;&nbsp;"
        = link_to '削除', capital, method: :delete, data: { confirm: "\n#{capital.yyyy}年を削除します。よろしいですか？"  }, class: 'btn btn-danger' 

br
= link_to '会計年度の新規登録', new_fsjs_capital_path,class: 'btn btn-primary'  

br
br
br

nav aria-label="breadcrumb"
  ol.breadcrumb
    li.breadcrumb-item =link_to("ホーム", root_path) 
    li.breadcrumb-item.active aria-current="page" = '会計年度'

p        

app/views/fsjs_capitals/new.html.slim
- provide(:title, '会計年度 - 新規登録')
- provide(:submit, '登録する')

nav aria-label="breadcrumb"
  ol.breadcrumb
    li.breadcrumb-item =link_to("ホーム", root_path) 
    li.breadcrumb-item =link_to("会計年度", fsjs_capitals_path)     
    li.breadcrumb-item.active aria-current="page" = '新規作成'

p
h1 新規登録 - 会計年度
p

= render 'form'

br
br
= link_to '戻る', fsjs_capitals_path
p

nav aria-label="breadcrumb"
  ol.breadcrumb
    li.breadcrumb-item =link_to("ホーム", root_path) 
    li.breadcrumb-item =link_to("会計年度", fsjs_capitals_path)     
    li.breadcrumb-item.active aria-current="page" = '新規作成'
p

app/views/fsjs_capitals/show.html.slim
- provide(:title, '会計年度 - 表示')

nav aria-label="breadcrumb"
  ol.breadcrumb
    li.breadcrumb-item =link_to("ホーム", root_path) 
    li.breadcrumb-item =link_to("会計年度", fsjs_capitals_path)     
    li.breadcrumb-item.active aria-current="page" = '表示'

table.table.table-hover 
  tr
    th style="width:200px;" = FsjsCapital.human_attribute_name(:yyyy)
    td = @fsjs_capital.yyyy
  tr
    th = FsjsCapital.human_attribute_name(:m1)
    td = @fsjs_capital.m1.to_s(:delimited)  
  tr
    th = FsjsCapital.human_attribute_name(:m2)
    td = @fsjs_capital.m2.to_s(:delimited)  
  tr
    th = FsjsCapital.human_attribute_name(:m3)
    td = @fsjs_capital.m3.to_s(:delimited)  
  tr
    th = FsjsCapital.human_attribute_name(:m4)
    td = @fsjs_capital.m4.to_s(:delimited)  


div
  div.float-right
    span = link_to '編集', edit_fsjs_capital_path(@fsjs_capital), class: 'btn btn-primary' 
    span = raw "&nbsp;&nbsp;&nbsp;"
    span = link_to '削除', @fsjs_capital, data: { confirm: "\n#{@fsjs_capital.yyyy}年を削除します。\nよろしいですか？" }, method: :delete, class: 'btn btn-danger' 
  div.float-left
    = link_to '戻る', fsjs_capitals_path
div.clearfix    

p

nav aria-label="breadcrumb"
  ol.breadcrumb
    li.breadcrumb-item =link_to("ホーム", root_path) 
    li.breadcrumb-item =link_to("会計年度", fsjs_capitals_path)     
    li.breadcrumb-item.active aria-current="page" = '表示'
    
p    