config/routes.rb
Rails.application.routes.draw do

  root to: 'fsjs_main#index'
  resources :fsjs_capitals
  resources :fsjs_journals
  resources :fsjs_accounts
  
  get  '/login', to: 'fsjs_login#new'
  post '/login', to: 'fsjs_login#create'
  delete '/logout', to: 'fsjs_login#destroy'
  
end

app/models/fsjs_journal.rb
class FsjsJournal < ApplicationRecord
  validates :yyyy,  presence: true
  validates :yyyy, numericality: { greater_than_or_equal_to: 1989, less_than_or_equal_to: 2099 } , unless: Proc.new { |a| a.yyyy.blank? }
  validates :mm,  presence: true
  validates :mm,   numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 12 } , unless: Proc.new { |a| a.mm.blank? } 
  validates :dd,  presence: true
  validates :dd,   numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 31 } , unless: Proc.new { |a| a.dd.blank? } 
  validates :debit_account_id,  presence: true
  validates :credit_account_id,  presence: true
  validates :money,  presence: true, length: { maximum: 10 }
  validates :money,  numericality: { greater_than_or_equal_to: 1 } , unless: Proc.new { |a| a.money.blank? }   
  validates :summary,  presence: true, length: { maximum: 50 }   
  
  # -------------------
  #  メソッド
  # -------------------
  # 対象科目の合計金額を取得する
  def get_account_total(obj,target_id,edit_id)
  
    if (money.blank?)
      return 0
    end
    
    if (!(credit_account_id == target_id ||  debit_account_id == target_id))
      return 0  
    end
       
    # 元入金テーブル
    capital = FsjsCapital.where(yyyy: yyyy) 
    
    # [編集]
    if edit_id.present?
      # 借方
      sql = "SELECT IFNULL(SUM(money),0) AS money  FROM fsjs_journals WHERE yyyy = ? AND debit_account_id = ? AND id <> ?"
      debit = FsjsJournal.find_by_sql([sql,yyyy,target_id,edit_id]) 
      # 貸方
      sql = "SELECT IFNULL(SUM(money),0) AS money  FROM fsjs_journals WHERE yyyy = ? AND credit_account_id = ? AND id <> ?"
      credit = FsjsJournal.find_by_sql([sql,yyyy,target_id,edit_id])            
    # [新規登録]
    else
      # 借方
      sql = "SELECT IFNULL(SUM(money),0) AS money  FROM fsjs_journals WHERE yyyy = ? AND debit_account_id = ?"
      debit = FsjsJournal.find_by_sql([sql,yyyy,target_id]) 
      # 貸方
      sql = "SELECT IFNULL(SUM(money),0) AS money  FROM fsjs_journals WHERE yyyy = ? AND credit_account_id = ?"
      credit = FsjsJournal.find_by_sql([sql,yyyy,target_id])         
    end
             
    # 未払金
    if (target_id == 5) 
          
      # 借方
      if debit_account_id == target_id      
        total = (debit[0][:money] + money) - (capital[0][obj] + credit[0][:money]) 
      # 貸方  
      else
        total = (debit[0][:money]) - (capital[0][obj] + credit[0][:money] + money) 
      end       

    # 現金、その他の預金、前払金
    else
      
      # 借方
      if debit_account_id == target_id
        total = (capital[0][obj] + debit[0][:money] + money) - credit[0][:money]
      # 貸方  
      else
        total = (capital[0][obj] + debit[0][:money]) - credit[0][:money] - money
      end
    end    
            
    total
  end    
    
  # -------------------
  #  カスタムメソッド
  # -------------------
  
  # 同一科目
  validate :same_account_id
  def same_account_id
    if debit_account_id.present?
      if debit_account_id ==  credit_account_id
        errors.add(:debit_account_id, "と科目(貸方)には同じ科目を登録できません")
      end   
    end 
  end  
    
  # 各科目の合計金額の整合性を確認する
  validate :money_check
  def money_check
    
    # 仕訳帳は1/1から順番に記帳しないと矛盾が生じてエラーが多発しやすいです。
    # エラーチェックを解除したい場合は次のコードを有効にして下さい。
    # return
  
    # 現金 
    total = get_account_total(:m1,3,id)
    if(total < 0)
      errors.add(:dummy, "現金の合計が"+ total.to_s(:delimited) +"円になります。この仕訳の前に「借方」に現金を追加して下さい 例)借方(現金) 貸方(事業主借)")
    end
    
    # その他の預金 
    total = get_account_total(:m2,4,id)
    if(total < 0)
      errors.add(:dummy, "その他の預金の合計が"+ total.to_s(:delimited) +"円になります。※他の仕訳の「その他の預金」を確認して下さい")
    end
    
    # 前払金 
    total = get_account_total(:m3,13,id)
    if(total < 0)
      errors.add(:dummy, "前払金の合計が"+ total.to_s(:delimited) +"円になります。※他の仕訳の「前払金」を確認して下さい")
    end
    
    # 未払金 
    total = get_account_total(:m4,5,id)
    if(total > 0)
      errors.add(:dummy, "このままだと未払金を支払い過ぎます。("+ total.to_s(:delimited) +"円多い) ※他の仕訳の「未払金」を確認して下さい")
    end      
  end  
end

app/controllers/fsjs_journals_controller.rb
class FsjsJournalsController < ApplicationController
  before_action :set_fsjs_journal, only: [:show, :edit, :update, :destroy]

  before_action :fsjs_get_account_debits_combobox, :fsjs_get_account_credits_combobox
  helper_method :fsjs_get_account_from_id
  
  # GET /fsjs_journals
  def index
    if params[:yyyy].blank?
      redirect_to root_path
      return
    end
    @q = FsjsJournal.all.where(yyyy: params[:yyyy]).order(mm: "DESC", dd: "DESC",summary: "ASC", debit_account_id: "ASC")
    @fsjs_journals = @q.page(params[:page]).per(50) 
    
    sql = "SELECT id, name,expense_flg FROM fsjs_accounts WHERE types <> 2 ORDER BY sort_list ASC"
    db_data = FsjsAccount.find_by_sql(sql) 
    
    
    # 元入金テーブル
    @capital = FsjsCapital.where(yyyy: params[:yyyy]) 
    
    if @capital.blank?        
      @capital = []
      @capital[0] = {}
      @capital[0][:m1] =0
      @capital[0][:m2] =0
      @capital[0][:m3] =0
      @capital[0][:m4] =0        
    end
      
    # 現金
    @money = fsjs_get_account_total(params[:yyyy],:m1,3)
    # その他の預金
    @deposit = fsjs_get_account_total(params[:yyyy],:m2,4)
    # 前払金
    @advance_payment = fsjs_get_account_total(params[:yyyy],:m3,13)
    # 未払金
    @accounts_payable = fsjs_get_account_total(params[:yyyy],:m4,5)
    # 売上
    sql = "SELECT IFNULL(SUM(money),0) AS money FROM fsjs_journals WHERE yyyy = ? AND credit_account_id = 12"
    @sales = FsjsJournal.find_by_sql([sql,params[:yyyy]])[0][:money] 
          
  end

  # GET /fsjs_journals/1
  def show
  end

  # GET /fsjs_journals/new
  def new
    @fsjs_journal = FsjsJournal.new
    @fsjs_journal.yyyy = params[:yyyy]
  end

  # GET /fsjs_journals/1/edit
  def edit
  end

  # POST /fsjs_journals
  def create
    @fsjs_journal = FsjsJournal.new(fsjs_journal_params)

    respond_to do |format|
      if @fsjs_journal.save
        format.html { redirect_to fsjs_journals_path(yyyy: @fsjs_journal.yyyy), notice: '登録しました。' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /fsjs_journals/1
  def update
    respond_to do |format|
      if @fsjs_journal.update(fsjs_journal_params)
        format.html { redirect_to fsjs_journals_path(yyyy: @fsjs_journal.yyyy), notice: '更新しました。' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /fsjs_journals/1
  def destroy
    @fsjs_journal.destroy
    respond_to do |format|
      format.html { redirect_to fsjs_journals_path(yyyy: @fsjs_journal.yyyy), alert: '削除しました。' }
    end
  end
   
  private
    
    # コンボボックス用 - 借方
    def fsjs_get_account_debits_combobox()
      sql = "SELECT id, name,expense_flg FROM fsjs_accounts WHERE types <> 2 ORDER BY sort_list ASC"
      db_data = FsjsAccount.find_by_sql(sql) 
      
      @fsjs_account_debits_list = []
      db_data.each_with_index  do |obj, i|
        if(obj['expense_flg'])
          @fsjs_account_debits_list.push(["[経費]" +obj['name'],obj['id']])
        else
          @fsjs_account_debits_list.push([obj['name'],obj['id']])
        end  
      end      
    end  
    
    # コンボボックス用 - 貸方
    def fsjs_get_account_credits_combobox()
      sql = "SELECT id, name FROM fsjs_accounts WHERE types <> 1 ORDER BY sort_list ASC"
      db_data = FsjsAccount.find_by_sql(sql) 
      
      @fsjs_account_credits_list = []
      db_data.each_with_index  do |obj, i|
        @fsjs_account_credits_list.push([obj['name'],obj['id']])
      end      
    end      
    
    # idから種類を取得する 
    def fsjs_get_account_from_id(id)    
      db_data = FsjsAccount.find_by_sql(["SELECT name FROM fsjs_accounts WHERE id = ?",id]) 
      db_data[0]['name']    
    end      
      
    # Use callbacks to share common setup or constraints between actions.
    def set_fsjs_journal
      @fsjs_journal = FsjsJournal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fsjs_journal_params
      params.require(:fsjs_journal).permit(:yyyy, :mm, :dd, :debit_account_id, :credit_account_id, :money, :summary)
    end
end

app/helpers/fsjs_journals_helper.rb
module FsjsJournalsHelper
end

app/views/fsjs_journals/_form.html.slim
= form_with(model: @fsjs_journal, local: true) do |f|
  - if @fsjs_journal.errors.any?
    #error_explanation.text-danger
      ul
        - @fsjs_journal.errors.full_messages.each do |message|
          li = message

  div.alert.alert-primary role="alert" =  '日付'
  .form-group
    = @fsjs_journal.yyyy.to_s() +"年"
    = f.hidden_field :yyyy, class: 'form-control', id: 'fsjs_journal_yyyy'  
  .form-group
    = f.label :mm
    = f.number_field :mm, class: 'form-control', id: 'fsjs_journal_mm'
  .form-group
    = f.label :dd
    = f.number_field :dd, class: 'form-control', id: 'fsjs_journal_dd'

  div.alert.alert-primary role="alert" =  '借方 ※大まかに言うとプラスのイメージ'
    
  .form-group
    - if @fsjs_journal.debit_account_id?    
      = f.select :debit_account_id, options_for_select(@fsjs_account_debits_list,@fsjs_journal.debit_account_id),include_blank: '選択して下さい。',id: 'fsjs_journal_debit_account_id'
    - else
      = f.select :debit_account_id, options_for_select(@fsjs_account_debits_list),include_blank: '選択して下さい。',id: 'fsjs_journal_debit_account_id'   

  div.alert.alert-primary role="alert" =  '貸方 ※大まかに言うとマイナスのイメージ'
    
  .form-group
    - if @fsjs_journal.credit_account_id?    
      = f.select :credit_account_id, options_for_select(@fsjs_account_credits_list,@fsjs_journal.credit_account_id),include_blank: '選択して下さい。',id: 'fsjs_journal_credit_account_id'
    - else
      = f.select :credit_account_id, options_for_select(@fsjs_account_credits_list),include_blank: '選択して下さい。',id: 'fsjs_journal_credit_account_id'   

  div.alert.alert-primary role="alert" =  '金額'
  .form-group
    = f.number_field :money, class: 'form-control', id: 'fsjs_journal_money'
    
  div.alert.alert-primary role="alert" =  '摘要'
  .form-group
    p 
      = "(例)1/24 ご依頼○○様、○○広告収入、○○銀行、 クレジットカード(○○代)、○○引き落とし、携帯通信料金(按分50%)など"
    = f.text_field :summary, class: 'form-control', id: 'fsjs_journal_summary'
  
  br
  br    
  = f.submit yield(:submit) , class: 'btn btn-primary'  

= raw "\n"
= raw '<script>' + "\n"
= raw 'function run(){' + "\n"
= raw '  var obj = document.getElementById("input_assistance");' + "\n"
= raw '  document.getElementById("fsjs_journal_summary").value = obj.options[obj.selectedIndex].text' + "\n"
= raw '}' + "\n"
= raw '</script>' + "\n"

app/views/fsjs_journals/edit.html.slim
- provide(:title, '仕訳 - 編集')
- provide(:submit, '更新する')

nav aria-label="breadcrumb"
  ol.breadcrumb
    li.breadcrumb-item =link_to("ホーム", root_path) 
    li.breadcrumb-item =link_to("会計年度", fsjs_capitals_path)     
    li.breadcrumb-item.active aria-current="page" = '仕訳の編集'

p
h1 仕訳の編集
p

= render 'form'

br
br
= link_to '戻る', fsjs_journals_path(yyyy:  @fsjs_journal.yyyy)
p

nav aria-label="breadcrumb"
  ol.breadcrumb
    li.breadcrumb-item =link_to("ホーム", root_path) 
    li.breadcrumb-item =link_to("会計年度", fsjs_capitals_path)     
    li.breadcrumb-item.active aria-current="page" = '仕訳の編集'

p    

app/views/fsjs_journals/index.html.slim
- provide(:title, '仕訳帳')

nav aria-label="breadcrumb"
  ol.breadcrumb
    li.breadcrumb-item =link_to("ホーム", root_path) 
    li.breadcrumb-item =link_to("会計年度", fsjs_capitals_path)     
    li.breadcrumb-item.active aria-current="page" = '仕訳帳'
    
p
h1 ="仕訳帳("+ params[:yyyy] + "年)"
p

p = "仕訳は1/1から順番に登録して下さい。現金、その他の預金、前払金、未払金は入力誤り判定機能付きです。"

p = link_to '仕訳の新規登録', new_fsjs_journal_path(yyyy: params[:yyyy]),class: 'btn btn-primary'  

h5 =  "[ 基本情報 ]" 
p
table.table.table-hover 
  tr
    th 元入金
    td
      = " 現金 : " + @capital[0][:m1].to_s(:delimited)
      = " その他の預金 : " + @capital[0][:m2].to_s(:delimited)
      = " 前払金 : " + @capital[0][:m3].to_s(:delimited)
      = " 未払金 : " + @capital[0][:m4].to_s(:delimited)  
  tr
    th 12/31(期末)
    td
      = " 現金 : " + @money.to_s(:delimited)
      = " その他の預金 : " + @deposit.to_s(:delimited)
      = " 前払金 : " + @advance_payment.to_s(:delimited)
      = " 未払金 : " + @accounts_payable.to_s(:delimited)  
      = " 売上 : " + @sales.to_s(:delimited)
      
p
h5 =  "[ 仕訳 ]"
p

table.table.table-hover 
  thead
    tr
      th = "日付"
      th = "借方"
      th = "貸方"
      th = FsjsJournal.human_attribute_name(:money)
      th = FsjsJournal.human_attribute_name(:summary)      
      th
  - @fsjs_journals.each do |journal|
    tr
      td
        = link_to (sprintf("%02d",journal.mm)  + "/" +  sprintf("%02d",journal.dd)), journal
      td
        = fsjs_get_account_from_id(journal.debit_account_id)
      td
        = fsjs_get_account_from_id(journal.credit_account_id)
      td
        = journal.money.to_s(:delimited)         
      td style="width:300px;"
        = journal.summary
      td
        = link_to '編集', edit_fsjs_journal_path(journal), class: 'btn btn-primary' 
        = raw "&nbsp;&nbsp;&nbsp;"
        = link_to '削除', journal, method: :delete, data: { confirm: "\n#{journal.mm}/#{journal.dd}の仕訳を削除します。よろしいですか？"  }, class: 'btn btn-danger' 

.mb-3
  = paginate @fsjs_journals
  = page_entries_info @fsjs_journals
  
br

nav aria-label="breadcrumb"
  ol.breadcrumb
    li.breadcrumb-item =link_to("ホーム", root_path) 
    li.breadcrumb-item =link_to("会計年度", fsjs_capitals_path)     
    li.breadcrumb-item.active aria-current="page" = '仕訳帳'

p      

app/views/fsjs_journals/new.html.slim
- provide(:title, '仕訳 - 新規登録')
- provide(:submit, '登録する')

nav aria-label="breadcrumb"
  ol.breadcrumb
    li.breadcrumb-item =link_to("ホーム", root_path) 
    li.breadcrumb-item =link_to("会計年度", fsjs_capitals_path)     
    li.breadcrumb-item.active aria-current="page" = '仕訳の新規登録'

p
h1 仕訳の新規登録
p

= render 'form'

br
br
= link_to '戻る', fsjs_journals_path(yyyy:  @fsjs_journal.yyyy)
p

nav aria-label="breadcrumb"
  ol.breadcrumb
    li.breadcrumb-item =link_to("ホーム", root_path) 
    li.breadcrumb-item =link_to("会計年度", fsjs_capitals_path)     
    li.breadcrumb-item.active aria-current="page" = '仕訳の新規登録'

app/views/fsjs_journals/show.html.slim
- provide(:title, '仕訳 - 表示')

nav aria-label="breadcrumb"
  ol.breadcrumb
    li.breadcrumb-item =link_to("ホーム", root_path) 
    li.breadcrumb-item =link_to("会計年度", fsjs_capitals_path)     
    li.breadcrumb-item.active aria-current="page" = '仕訳の表示'

table.table.table-hover 
  tr
    th = "日付"
    td = sprintf("%04d/%02d/%02d",@fsjs_journal.yyyy,@fsjs_journal.mm,@fsjs_journal.dd)
  tr
    th = "借方"
    td = fsjs_get_account_from_id(@fsjs_journal.debit_account_id)
  tr
    th = "貸方"
    td = fsjs_get_account_from_id(@fsjs_journal.credit_account_id)
  tr
    th = "金額"
    td = @fsjs_journal.money.to_s(:delimited) 
    
  tr
    th = "摘要"
    td = @fsjs_journal.summary 
  tr
    th = "最終更新日"
    td = @fsjs_journal.updated_at.to_s.sub(/\+0900/, '') 

div
  div.float-right
    span = link_to '編集', edit_fsjs_journal_path(@fsjs_journal), class: 'btn btn-primary' 
    span = raw "&nbsp;&nbsp;&nbsp;"
    span = link_to '削除', @fsjs_journal, data: { confirm: "\n#{@fsjs_journal.yyyy}/#{@fsjs_journal.mm}/#{@fsjs_journal.dd}の仕訳を削除します。よろしいですか？" }, method: :delete, class: 'btn btn-danger' 
  div.float-left
    = link_to '戻る', fsjs_journals_path(yyyy:  @fsjs_journal.yyyy)
div.clearfix    

p

nav aria-label="breadcrumb"
  ol.breadcrumb
    li.breadcrumb-item =link_to("ホーム", root_path) 
    li.breadcrumb-item =link_to("会計年度", fsjs_capitals_path)     
    li.breadcrumb-item.active aria-current="page" = '仕訳の表示'
    
p 